# serverless.yml

service: "qrcoder"

stage: local
region: us-east-1

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'local'}
  memorySize: 256
  timeout: 10

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - ${opt:stage, 'local'}
    autostart: false
    debug: true
    docker:
      sudo: false
    host: http://172.16.0.11

functions:
  qrcoder:
    handler: bin/qr
