# serverless.yml

service: "qrcoder"

stage: dev
region: us-east-1

plugins:
  - serverless-apigw-binary
  - serverless-apigwy-binary
  - serverless-api-cloudfront

custom:
  domain: qrcoder.vitorhrmiranda.com.br
  bucket: qrcoder-vitorhrmiranda-com-br
  certificate: arn:aws:acm:us-east-1:838466458684:certificate/0d0a3e27-0e8a-467b-b6e3-ad8abded2f5a
  apigwBinary:
    types:
      - "image/png"
      - "*/*"
  apiCloudFront:
    domain: ${self:custom.domain}
    certificate: ${self:custom.certificate}
    logging:
      bucket: ${self:custom.bucket}.s3.amazonaws.com
      prefix: ${self:provider.stage}
    cookies: none
    querystring:
      - size
      - body
      - ext

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 10

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  qrcoder:
    handler: bin/qr
    events:
      - http:
          path: create
          method: get
          contentHandling: CONVERT_TO_BINARY

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
  Outputs:
    ApiDistribution:
      Description: "ApiDistribution"
      Value: ApiDistribution
